---
- name: Download Jenkins CLI
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "/tmp/jenkins-cli.jar"

- name: Install suggested plugins
  command: >
    java -jar /tmp/jenkins-cli.jar -s {{ jenkins_url }} 
    -auth {{ jenkins_admin_username }}:{{ jenkins_admin_password }}
    install-plugin {{ item }}
  loop:
    - git
    - workflow-aggregator
    - ssh-slaves
    - matrix-auth
  register: install_plugins
  changed_when: "'Plugin already installed' not in install_plugins.stdout"

- name: Create Jenkins init.groovy.d directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy create-user Groovy script
  template:
    src: create-user.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/create-user.groovy"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Disable initial setup wizard
  copy:
    content: "2.0"
    dest: "{{ jenkins_home }}/jenkins.install.InstallUtil.lastExecVersion"

- name: Disable upgrade wizard
  copy:
    content: "2.0"
    dest: "{{ jenkins_home }}/jenkins.install.UpgradeWizard.state"
  notify: Restart Jenkins