# SSH ports declaration
# jenkins: 8000
# jenkinsSlave: 8001
# sonarDatabase: 8002
# sonar: 8003
# sonatypeDatabase: 8004
# sonatype: 8005

version: '3'
services:

  jenkins:
    image: ubuntu-sshd-with-sudo:latest
    container_name: jenkins
    ports:
      - "8000:22"
      - "8080:8080"
    expose:
      - "50000"
    environment:
      - SSH_USERNAME=jenkinsSSH
      - PASSWORD=jenkinsSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  jenkinsSlave:
    image: ubuntu-sshd-with-sudo:latest
    container_name: jenkinsSlave
    ports:
      - "8001:22"
    environment:
      - SSH_USERNAME=jenkinsSlaveSSH
      - PASSWORD=jenkinsSlaveSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  sonarDatabase:
    image: ubuntu-sshd-with-sudo:latest
    container_name: sonarDatabase
    ports:
      - "8002:22"
    expose: 
      - "5432"
    environment:
      - SSH_USERNAME=sonarDatabaseSSH
      - PASSWORD=sonarDatabaseSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network
    
  sonar:
    image: ubuntu-sshd-with-sudo:latest
    container_name: sonar
    ports:
      - "8003:22"
      - "9000:9000"
      - "9001:9001"
    environment:
      - SSH_USERNAME=sonarSSH
      - PASSWORD=sonarSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  nexusDatabase:
    image: ubuntu-sshd-with-sudo:latest
    container_name: nexusDatabase
    ports:
      - "8004:22"
    expose:
      - "5432"
    environment:
      - SSH_USERNAME=nexusDatabaseSSH
      - PASSWORD=nexusDatabaseSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

  nexus:
    image: ubuntu-sshd-with-sudo:latest
    container_name: nexus
    ports:
      - "8005:22"
      - "8081:8081"
    environment:
      - SSH_USERNAME=nexusSSH
      - PASSWORD=nexusSSH
      - AUTHORIZED_KEYS=${SSH_PUBLIC_KEY}
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge